description          = nerfed
min_minetest_version = 5.0
name                 = bonemeal
optional_depends     = default, mcl_core, lucky_block, farming, ethereal, moretrees, technic_worldgen, flowers, dye, ferns, dryplants, df_trees, df_farming, df_primordial_items, everness, technic
title                = IA Bonemeal
